# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: kitware/cmb:ci-cmb-fedora31-latest

    steps:
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        alias pvpython='/root/misc/root/smtk-deps/bin/pvpython'
        cd dev/cmb/simulation-workflows/ats/internal
        python3 build_ats.py
        pvpython run_unittests.py
