# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-latest
    container: kitware/cmb:ci-cmb-fedora31-latest
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: 'true'
      - name: Add pvpython to path
        run: echo '::add-path::/root/misc/root/smtk-deps/bin/'
      - name: Build Templates
        run: |
          cd dev/cmb/simulation-workflows/ats/internal
          python3 build_ats.py
      - name: Testing Suite
        run: |
          cd dev/cmb/simulation-workflows/
          pvpython run_unittests.py
      - name: Demos
        run: |
          cd dev/cmb/demo
          ./make_resources.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ats-cmb
          path: dev/cmb/simulation-workflows/ats
      - name: test on tags
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: echo "this was run"
